import image1 from "@/assets/package-1.jpg";
import image2 from "@/assets/package-2.jpg";
import image3 from "@/assets/package-3.jpg";
import image4 from "@/assets/package-4.jpg";
import image5 from "@/assets/package-5.jpg";
import image6 from "@/assets/package-6.jpg";

export const packages = [
  {
    name: "Bali South",
    slug: "bali-south",
    destination: [
      "Water sport",
      "Garuda Wisnu statue",
      "Uluwatu temple",
      "Water Blow",
      "Jimbaran bay",
    ],
    price: ["40 USD (10 Hours)"],
    titleDesc: "Exploring South Bali offers a diverse experience",
    desc: [
      "Water Sports: Enjoy thrilling water activities in areas like Tanjung Benoa, offering a range of options such as parasailing, jet-skiing, and banana boat rides.",
      "Garuda Wisnu Statue: Marvel at the iconic Garuda Wisnu Kencana (GWK) statue, a cultural landmark representing the Hindu god Vishnu riding the mythical bird Garuda.",
      "Uluwatu Temple: Visit Uluwatu Temple perched on a cliff, offering breathtaking views of the Indian Ocean. Enjoy the traditional Kecak dance performances during sunset.",
      "Water Blow: Witness the natural phenomenon at Water Blow in Nusa Dua, where powerful waves crash against the rocks, creating a spectacular water display.",
      "Jimbaran Bay: Indulge in a romantic dinner by the beach at Jimbaran Bay, known for its seafood restaurants offering a picturesque setting.",
      "These attractions showcase the diverse and enchanting offerings of South Bali.",
    ],
    include: "Driver, car, mineral water, parking ticket.",
    addition: "The itinerary can be changed according to your needs",
    extra: "Extra time 4US$/Hour",
    note: "Bring space clothes",
    imageUrl: image1,
  },
  {
    name: "East Bali Trip",
    slug: "east-bali-trip",
    destination: [
      "Heaven Gate Temple",
      "Tirta Gangga",
      "Taman Ujung",
      "Coffe Plantation",
    ],
    price: ["50 USD (10 Hours)"],
    titleDesc: "Explore the enchanting side of Bali with these destinations",
    desc: [
      "Heaven Gate Temple (Lempuyang Temple): Experience the breathtaking views of the iconic Heaven Gate at Lempuyang Temple. Capture the stunning Balinese gates with the backdrop of Mount Agung.",
      "Tirta Gangga: Immerse yourself in the beauty of Tirta Gangga Water Palace. Wander through lush gardens, ornate pools, and historic structures, experiencing the serenity of this royal water palace.",
      "Taman Ujung: Visit Taman Ujung, a water palace with a blend of Balinese and European architectural influences. Enjoy scenic landscapes, expansive pools, and historic structures surrounded by lush greenery.",
      "These destinations offer a mix of cultural heritage, natural beauty, and the chance to indulge in the aromatic world of Balinese coffee",
    ],
    include: "Driver, car, mineral water, parking ticket.",
    addition: "The itinerary can be changed according to your needs",
    extra: "Extra time 4US$/Hour",
    note: "-",
    imageUrl: image2,
  },
  {
    name: "Bedugul Trip",
    slug: "bedugul-trip",
    destination: [
      "Handara Gates",
      "Temple on the lake",
      "Twin Lake",
      "Tanah Lot Temple",
    ],
    price: ["45 US$ (10 Hours)"],
    titleDesc: "Discover the cultural and scenic wonders of Bali",
    desc: [
      "Handara Gates: Pose for iconic photos at the Handara Gates, known for their picturesque setting. These traditional Balinese gates make for a memorable visit.",
      "Temple on the Lake: Explore Ulun Danu Beratan Temple, located on the shores of Lake Bratan. This water temple is not only a spiritual site but also offers stunning reflections against the lake backdrop.",
      "Twin Lake: Visit the serene Buyan and Tamblingan Twin Lakes in Bedugul. The twin lakes are nestled amidst lush greenery, providing a tranquil escape and breathtaking views.",
      "Tanah Lot Temple: Witness the magic of Tanah Lot, a sea temple perched on a rock formation. Enjoy the dramatic sunsets and the mystical atmosphere surrounding this iconic Balinese temple.",
      "These attractions offer a blend of cultural richness, natural beauty, and unique experiences in Bali",
    ],
    include: "Driver, car, mineral water, parking ticket.",
    addition: "The itinerary can be changed according to your needs",
    extra: "Extra time 4US$/Hour",
    note: "-",
    imageUrl: image3,
  },
  {
    name: "Ubud Activity 2",
    slug: "ubud-activity-2",
    destination: ["Rafting", "Swing", "Waterfall"],
    price: ["45 US$ (10 Hours)"],
    titleDesc: "Embark on a varied journey in Bali",
    desc: [
      "Rafting: Experience the thrill of white-water rafting on Bali's rivers, such as the Ayung River near Ubud. Navigate through lush landscapes and enjoy the adrenaline rush of this exciting water adventure.",
      "Swing: Try the famous Bali swings, like the ones in Ubud or Tegallalang. Soar high above the treetops and rice terraces, capturing stunning views and creating unforgettable memories.",
      "Waterfall: Chase the beauty of Bali's waterfalls, like Tegenungan or Gitgit. Immerse yourself in the natural surroundings, cool off in refreshing waters, and enjoy the tranquility of these cascading wonders.",
      "These activities promise a blend of excitement, cultural exploration, and natural serenity in the enchanting island of Bali.",
    ],
    include: "Driver, car, mineral water, parking ticket.",
    addition: "The itinerary can be changed according to your needs",
    extra: "Extra time 4US$/Hour",
    note: "Bring space clothes",
    imageUrl: image4,
  },
  {
    name: "Ubud Activity",
    slug: "ubud-activity",
    destination: ["ATV", "Rice Terrace", "Alas Harum", "Bali Bird"],
    price: ["45 US$ (10 Hours)"],
    titleDesc: "Explore the adventure and natural beauty of Bali",
    desc: [
      "ATV (Quad Biking): Take an exhilarating ATV ride through Bali's scenic landscapes, often including muddy tracks, rivers, and lush jungles for an adrenaline-pumping experience.",
      "Rice Terraces: Visit the breathtaking Tegallalang Rice Terraces in Ubud, known for their stunning green landscapes and intricate irrigation systems, offering a serene and picturesque setting.",
      "Alas Harum: Immerse yourself in the world of coffee and spices at Alas Harum Agro Tourism. Experience a coffee plantation tour, learn about the coffee-making process, and enjoy panoramic views of the surrounding area.",
      "Bali Bird Park: Explore the Bali Bird Park in Gianyar, home to a diverse collection of exotic birds. Witness fascinating bird shows and educational programs, making it a great destination for nature enthusiasts These attractions provide a mix of adventure, cultural exploration, and nature appreciation in Bali.",
    ],
    include: "Driver, car, mineral water, parking ticket.",
    addition: "The itinerary can be changed according to your needs",
    extra: "Extra time 4US$/Hour",
    note: "Bring space clothes",
    imageUrl: image5,
  },
  {
    name: "Nusa Penida Tour",
    slug: "nusa-penida-tour",
    destination: [
      "Kelingking Beach",
      "Angel's Billabong and Broken Beach",
      "Crystal Bay",
      "Atuh Beach",
    ],
    price: [
      "1 - 2 Person : 65 US$ Per Person",
      "3 - 4 Person : 55 US$ Per Person",
      "5 - 6 Person : 45 US$ Per Person",
      "Price are quoted per person for minimum booking is 2 person",
    ],
    titleDesc:
      "Nusa Penida, an island southeast of Bali, is known for its stunning landscapes and unique attractions",
    desc: [
      "Kelingking Beach: Marvel at the iconic T-Rex-shaped cliff and enjoy panoramic views of the turquoise waters at Kelingking Beach, one of Nusa Penida's most famous spots.",
      "Angel's Billabong and Broken Beach: Witness the natural beauty of Angel's Billabong, a natural infinity pool, and nearby Broken Beach, a dramatic coastal formation with a natural bridge.",
      "Crystal Bay: Relax on the white sandy beach and go snorkeling in the clear waters of Crystal Bay, known for its vibrant marine life.",
      "Atuh Beach: Visit Atuh Beach, featuring stunning rock formations, clear blue waters, and a tranquil atmosphere. Nusa Penida offers a blend of natural wonders, pristine beaches, and unique landscapes for those seeking a more off-the-beaten-path experience in Bali.",
    ],
    include:
      "Private Transport with Fully Air-Conditioning Car in Bali and Nusa Penida Island, Professional English Speaking Driver, Return Transfer Speedboat Ticket to Nusa Penida (Sharing Boat), All Entrance Ticket, Indonesian Set Menu Lunch and Mineral Water, Petrol, Parking Ticket, 21% Government Tax and Service",
    addition: "The itinerary can be changed according to your needs",
    extra: "",
    note: "",
    imageUrl: image6,
  },
];
